<?php

namespace App\Services\Incomes;

use App\Models\Transaction;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/**
 * Class DirectSalaryService
 *
 * BUSINESS INCOME RULE 5: DIRECT SALARY INCOME ON DIRECT BUSINESS (PDF Presentation Slide 17)
 * ---------------------------------------------------------------------------------------------
 * Description:
 * Stable daily recurring salary credited for 365 consecutive days based on total
 * direct sponsored active business volume generated by the member.
 *
 * Salary Tiers & Daily Payouts (365 Days Duration):
 * 1. Plan 1: $1,000 Direct Business  --> $1.00 / Day   ($365 Total Income)
 * 2. Plan 2: $5,000 Direct Business  --> $5.00 / Day   ($1,825 Total Income)
 * 3. Plan 3: $10,000 Direct Business --> $10.00 / Day  ($3,650 Total Income)
 * 4. Plan 4: $25,000 Direct Business --> $25.00 / Day  ($9,125 Total Income)
 * 5. Plan 5: $50,000 Direct Business --> $50.00 / Day  ($18,250 Total Income)
 * 6. Plan 6: $100,000 Direct Business--> $200.00 / Day ($73,000 Total Income)
 * 7. Plan 7: $250,000 Direct Business--> $500.00 / Day ($182,500 Total Income)
 * 8. Plan 8: $500,000 Direct Business--> $1,000.00 / Day ($365,000 Total Income)
 *
 * Conditions:
 * - Calculated based on total active direct referral business.
 * - Payout Frequency: Daily for 365 days.
 */
class DirectSalaryService
{
    /**
     * Direct Salary Tiers Definition Array.
     */
    public const SALARY_TIERS = [
        ['min_business' => 500000.00, 'daily_salary' => 1000.00, 'name' => '$500,000 Investment Plan'],
        ['min_business' => 250000.00, 'daily_salary' => 500.00,  'name' => '$250,000 Investment Plan'],
        ['min_business' => 100000.00, 'daily_salary' => 200.00,  'name' => '$100,000 Investment Plan'],
        ['min_business' => 50000.00,  'daily_salary' => 50.00,   'name' => '$50,000 Investment Plan'],
        ['min_business' => 25000.00,  'daily_salary' => 25.00,   'name' => '$25,000 Investment Plan'],
        ['min_business' => 10000.00,  'daily_salary' => 10.00,   'name' => '$10,000 Investment Plan'],
        ['min_business' => 5000.00,   'daily_salary' => 5.00,    'name' => '$5,000 Investment Plan'],
        ['min_business' => 1000.00,   'daily_salary' => 1.00,    'name' => '$1,000 Investment Plan'],
    ];

    /**
     * Calculate user's direct sponsored business and credit daily salary if eligible.
     *
     * @param  User  $user  Target user being evaluated.
     * @return float Amount of daily salary credited ($).
     */
    public function processUserDirectSalary(User $user): float
    {
        if ($user->status !== 'active') {
            return 0.00;
        }

        // Calculate total active business volume generated by direct referrals
        $directMembers = User::where('sponsor_code', $user->referral_code)
            ->where('status', 'active')
            ->with('userPackages')
            ->get();

        $totalDirectBusiness = 0.00;
        foreach ($directMembers as $member) {
            $totalDirectBusiness += $member->userPackages->where('status', 'active')->sum('invested_amount');
        }

        // Find highest matching salary tier
        $matchedTier = null;
        foreach (self::SALARY_TIERS as $tier) {
            if ($totalDirectBusiness >= $tier['min_business']) {
                $matchedTier = $tier;
                break;
            }
        }

        if (! $matchedTier) {
            return 0.00;
        }

        $dailySalaryAmount = $matchedTier['daily_salary'];

        DB::transaction(function () use ($user, $dailySalaryAmount, $matchedTier, $totalDirectBusiness) {
            $user->increment('earning_wallet', $dailySalaryAmount);

            Transaction::create([
                'user_id' => $user->id,
                'txn_number' => 'TXN-'.rand(10000000, 99999999),
                'wallet_type' => 'earning_wallet',
                'amount' => $dailySalaryAmount,
                'charge' => 0.00,
                'post_balance' => $user->fresh()->earning_wallet,
                'trx_type' => '+',
                'type' => 'direct_salary',
                'description' => 'Received Direct Salary Income of $'.number_format($dailySalaryAmount, 2)."/day ({$matchedTier['name']} for direct business volume of \$".number_format($totalDirectBusiness, 2).')',
                'status' => 'completed',
            ]);
        });

        return $dailySalaryAmount;
    }
}
